[tox]
envlist =
    py{39}-dj{42}-cms{41},
    py{310,311,312,313}-dj{42,50,51,52}-cms{41,50}

skip_missing_interpreters=True

[testenv]
deps =
    -r{toxinidir}/tests/requirements/base.txt
    dj42: Django>=4.2,<5.0
    dj50: Django>=5.0,<5.1
    dj51: Django>=5.1,<5.2
    dj52: Django>=5.2,<5.3
    cms41: django-cms>=4.1,<4.2
    cms50: django-cms>=5.0,<5.1

commands =
    {envpython} --version
    {env:COMMAND:coverage} erase
    {env:COMMAND:coverage} run tests/settings.py
    {env:COMMAND:coverage} report
